### ISSUE TITLE
Bugs during first launch of wizard

### ISSUE THREAD

**Issue by goerlibe** [discopop-project/discopop#260]
First Launch of the wizard fails.

```
starting DiscoPoP Wizard...

Traceback (most recent call last):
  File "/home/bg/.local/bin/discopop_wizard", line 8, in <module>
    sys.exit(main())
  File "/home/bg/.local/lib/python3.8/site-packages/discopop_wizard/__main__.py", line 30, in main
    wizard_main(convert_args(args))
  File "/home/bg/.local/lib/python3.8/site-packages/discopop_wizard/wizard.py", line 43, in main
    wizard = DiscoPoPConfigurationWizard(config_dir, arguments)
  File "/home/bg/.local/lib/python3.8/site-packages/discopop_wizard/wizard.py", line 87, in __init__
    self.initialize_screen(config_dir)
  File "/home/bg/.local/lib/python3.8/site-packages/discopop_wizard/wizard.py", line 96, in initialize_screen
    self.window.iconphoto(False, photo)
  File "/usr/lib/python3.8/tkinter/__init__.py", line 2127, in wm_iconphoto
    self.tk.call('wm', 'iconphoto', self._w, *args)
_tkinter.TclError: can't use "pyimage1" as iconphoto: not a photo image
```

If this code section is removed during the first launch, then it works and it can even be added again, to later show the icon (only the initial launch is problematic) :

```
photo = tk.PhotoImage(
file=os.path.join(str(pathlib.Path(__file__).parent.resolve()), "assets", "icons", "discoPoP_128x128.png"))
self.window.iconphoto(False, photo)
```

**Comment by lukasrothenberger** [comment]
is it still open?

**Comment by lukasrothenberger** [comment]
@goerlibe push.

**Comment by goerlibe** [comment]
seems to work fine
